coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.5%
    patch:
      default:
        target: 95%
        threshold: 0%
ignore:
  - "src/simple_ai_trading/__main__.py"
  - "tests/"

comment:
  require_changes: true
  after_n_builds: 1

codecov:
  notify:
    after_n_builds: 1
