"""Screen every complete new BTC/ETH/SOL 5m-to-15m interval composition."""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
from decimal import Decimal
import json
from pathlib import Path
import re
from typing import Any

from tools.adjudicate_polymarket_crypto_interval_composition import (
    _binary_market,
    _package,
)
from tools.adjudicate_polymarket_crypto_range_threshold_delta import _utc
from tools.adjudicate_polymarket_exact_mlb_monotone_prefilter import (
    _canonical_hash,
    _root_path,
    _sha256,
)


SCHEMA = "polymarket-crypto-interval-composition-delta-result-v1"
_SLUG = re.compile(r"^(btc|eth|sol)-updown-(5m|15m)-(\d+)$")
_RULES = {
    "BTC": [
        "time-weighted average price (TWAP) of Bitcoin, generated by Chainlink",
        "greater than or equal to the price at the beginning of that range",
        'Otherwise, it will resolve to "Down"',
        "BTC/USD TWAP data stream",
        "not according to any other sources or spot markets",
    ],
    "ETH": [
        "time-weighted average price (TWAP) of Ethereum, generated by Chainlink",
        "greater than or equal to the price at the beginning of that range",
        'Otherwise, it will resolve to "Down"',
        "ETH/USD TWAP data stream",
        "not according to any other sources or spot markets",
    ],
    "SOL": [
        "time-weighted average price (TWAP) of Solana, generated by Chainlink",
        "greater than or equal to the price at the beginning of that range",
        'Otherwise, it will resolve to "Down"',
        "SOL/USD TWAP data stream",
        "not according to any other sources or spot markets",
    ],
}


def _load(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_bytes())
    if not isinstance(value, dict):
        raise RuntimeError(f"{path.name} must contain an object")
    return value


def _validate_source(contract: dict[str, Any]) -> tuple[dict[str, Any], dict[str, Any]]:
    source_result_path = _root_path(contract["outputs"]["result_path"])
    source_result = _load(source_result_path)
    if (
        _canonical_hash(source_result, "result_sha256")
        != source_result.get("result_sha256")
        or source_result.get("contract")
        != {
            "path": contract["contract_path"],
            "sha256": contract["contract_sha256"],
        }
        or source_result.get("source_gate", {}).get("passed") is not True
    ):
        raise RuntimeError("source result binding failed")
    raw_path = _root_path(contract["outputs"]["raw_path"])
    raw = raw_path.read_bytes()
    receipt = source_result["capture"]["receipt"]
    if (
        receipt["url"] != contract["request"]["url"]
        or receipt["response_sha256"] != _sha256(raw)
        or receipt["response_bytes"] != len(raw)
        or receipt["status_code"] != 200
    ):
        raise RuntimeError("raw source binding failed")
    return _load(raw_path), source_result


def _new_events(
    payload: dict[str, Any], cutoff: datetime
) -> tuple[list[dict[str, Any]], bool, str | None]:
    values = payload.get("events")
    if not isinstance(values, list) or not all(isinstance(row, dict) for row in values):
        raise RuntimeError("events response must contain an object array")
    created = [_utc(row.get("createdAt")) for row in values]
    if created != sorted(created, reverse=True):
        raise RuntimeError("events are not ordered by descending createdAt")
    identities = [(str(row.get("id")), str(row.get("slug"))) for row in values]
    if len(identities) != len(set(identities)):
        raise RuntimeError("event identities are not unique")
    cursor = payload.get("next_cursor")
    cursor_value = None if cursor is None else str(cursor)
    crosses_cutoff = not values or created[-1] <= cutoff
    complete = crosses_cutoff
    return (
        [row for row, stamp in zip(values, created, strict=True) if stamp > cutoff],
        complete,
        cursor_value,
    )


def _intervals(
    events: list[dict[str, Any]], cutoff_text: str
) -> dict[tuple[str, str, int], dict[str, Any]]:
    rows: dict[tuple[str, str, int], dict[str, Any]] = {}
    for event in events:
        match = _SLUG.fullmatch(str(event.get("slug") or ""))
        if match is None:
            continue
        asset = match.group(1).upper()
        duration = match.group(2)
        start = int(match.group(3))
        row = _binary_market(
            event,
            {
                "slug": event["slug"],
                "title": event["title"],
                "start_epoch_seconds": start,
                "created_after_utc": cutoff_text,
            },
            _RULES[asset],
        )
        key = (asset, duration, start)
        if key in rows:
            raise RuntimeError("duplicate interval identity")
        rows[key] = row
    return rows


def _packages(rows: dict[tuple[str, str, int], dict[str, Any]]) -> list[dict[str, Any]]:
    packages: list[dict[str, Any]] = []
    for asset in sorted(_RULES):
        starts = sorted(
            start
            for row_asset, duration, start in rows
            if row_asset == asset and duration == "15m"
        )
        for start in starts:
            keys = [
                (asset, "5m", start),
                (asset, "5m", start + 300),
                (asset, "5m", start + 600),
                (asset, "15m", start),
            ]
            if not all(key in rows for key in keys):
                continue
            shorts = [rows[key] for key in keys[:3]]
            long = rows[keys[3]]
            packages.extend(
                {
                    "group_start_epoch_seconds": start,
                    **_package(
                        asset=asset,
                        direction=direction,
                        shorts=shorts,
                        long=long,
                    ),
                }
                for direction in ("up_chain", "down_chain")
            )
    return sorted(
        packages,
        key=lambda row: (
            Decimal(row["displayed_price_sum_pUSD"]),
            row["asset"],
            row["group_start_epoch_seconds"],
            row["direction"],
        ),
    )


def run(contract_path: Path) -> dict[str, Any]:
    contract_path = contract_path.resolve()
    contract = _load(contract_path)
    if _canonical_hash(contract, "contract_sha256") != contract.get("contract_sha256"):
        raise RuntimeError("contract hash mismatch")
    if contract_path != _root_path(contract["contract_path"]):
        raise RuntimeError("contract path mismatch")
    frozen = _utc(contract["frozen_at_utc"])
    if frozen > datetime.now(timezone.utc):
        raise RuntimeError("frozen timestamp is in the future")
    implementation = _root_path(contract["implementation"]["path"])
    if _sha256(implementation.read_bytes()) != contract["implementation"]["sha256"]:
        raise RuntimeError("implementation hash mismatch")
    for source in contract["prior_sources"]:
        path = _root_path(source["path"])
        if _sha256(path.read_bytes()) != source["sha256"]:
            raise RuntimeError("prior source hash mismatch")
    payload, source_result = _validate_source(contract)
    cutoff_text = contract["population"]["created_after_utc"]
    cutoff = _utc(cutoff_text)
    events, population_complete, cursor = _new_events(payload, cutoff)
    rows = _intervals(events, cutoff_text) if population_complete else {}
    packages = _packages(rows) if population_complete else []
    candidates = [row for row in packages if row["passes_strict_displayed_gross_gate"]]
    best = packages[0] if packages else None
    status = "new_event_delta_incomplete_stop_without_books"
    if population_complete and not events:
        status = "complete_delta_has_no_new_events"
    elif population_complete and not packages:
        status = "complete_delta_has_no_exact_interval_composition"
    elif population_complete and not candidates:
        status = "complete_delta_rejected_before_books_fees_and_accounts"
    elif population_complete:
        status = "strict_displayed_candidate_requires_separate_exact_book_contract"
    result: dict[str, Any] = {
        "schema_version": SCHEMA,
        "created_at_utc": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "contract": {
            "path": contract["contract_path"],
            "sha256": contract["contract_sha256"],
        },
        "retained_source": {
            "raw_path": contract["outputs"]["raw_path"],
            "raw_sha256": source_result["capture"]["receipt"]["response_sha256"],
            "source_result_sha256": source_result["result_sha256"],
            "network_requests_added_by_adjudication": 0,
        },
        "population": {
            "created_after_utc": cutoff_text,
            "returned_event_count": len(payload.get("events", [])),
            "new_event_count": len(events),
            "cursor": cursor,
            "complete_nonoverlapping_delta": population_complete,
            "eligible_interval_market_count": len(rows),
            "complete_aligned_group_count": len(packages) // 2,
        },
        "screen": {
            "package_count": len(packages),
            "packages_ranked_by_displayed_sum": packages,
            "strict_displayed_candidate_count": len(candidates),
            "best_package": best,
            "gamma_role": "rejection_only_never_acceptance_or_promotion_evidence",
        },
        "adjudication": {
            "status": status,
            "accepted_edge": False,
            "deployment_ready": False,
            "profitability_claim": False,
            "book_request_permitted": bool(population_complete and candidates),
            "next_action": (
                "freeze one exact current-fee and token-book batch for only the deterministic best candidate"
                if population_complete and candidates
                else "stop without books fees accounts credentials orders or funds"
            ),
        },
        "authority": contract["authority"],
        "implementation": contract["implementation"],
    }
    result["result_sha256"] = _canonical_hash(result, "result_sha256")
    output = _root_path(contract["adjudication_output_path"])
    if output.exists():
        raise RuntimeError("one-use adjudication output already exists")
    output.write_text(
        json.dumps(result, sort_keys=True, separators=(",", ":"), ensure_ascii=True)
        + "\n",
        encoding="ascii",
        newline="\n",
    )
    return result


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--contract", type=Path, required=True)
    args = parser.parse_args()
    result = run(args.contract)
    print(
        json.dumps(
            {
                "status": result["adjudication"]["status"],
                "new_events": result["population"]["new_event_count"],
                "complete_groups": result["population"]["complete_aligned_group_count"],
                "packages": result["screen"]["package_count"],
                "candidates": result["screen"]["strict_displayed_candidate_count"],
                "network_requests": 0,
                "payloads_printed": 0,
            },
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
